name: comment

on:
  issue_comment:
    types:
      - created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-20.04
    steps:
      - name: dump event details
        id: dump_evemt
        run: |
          jq < $GITHUB_EVENT_PATH
      - name: comment on commented PR
        id: coment_pr
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Comment on PR #${{ github.event.issue.number }}'
            })
