name: comment

on:
  issue_comment:
    types:
      - created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    # Run the action only for '/rerun' pull request comment by owner, member, or collaborator of the repo/organization
    if: |
      github.event.issue.pull_request
      && github.event.comment.body == '/rerun'
      && contains(fromJson('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-20.04
    steps:
      - name: dump event details
        id: dump_evemt
        run: |
          jq < $GITHUB_EVENT_PATH
      - name: comment on commented PR
        id: coment_pr
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Comment on PR #${{ github.event.issue.number }}'
            })

      - name: get pull request number
        id: pr_nr
        echo "${{ github.event.comment.issue_url }}"
        # TODO: store in var? echo "${X##*/}"

      #- name: checkout
        ## the correct way to checkout would be to use simmilar approach as in get_commit_by_timestamp function of the
        ## github gluetool module
        #uses: actions/checkout@v2
        #with:
          ## avoid checking out the default pull/NNN/head ref, as that gives
          ## mismatching SHAs in generated tarballs
          #ref: "${{ github.event.pull_request.head.sha || github.sha }}"

      #- name: trigger copr build
        #id: copr_build
        #run: |
          #make copr_build
